### ISSUE TITLE
liblcp.a binary

### ISSUE THREAD

**Issue by danielweck** [readium/r2-lcp-client-swift#1]
https://github.com/readium/r2-lcp-client-swift/blob/master/liblcp.a
DO NOT COMMIT THIS FILE FOR LCP profile `1.0` !!

**Comment by danielweck** [comment]
Also, ideally this 10MB binary file (static lib) should not be stored in this repository at all. It gets compiled from an external repository, so there should be included as a build step, or from a separate storage facility for prebuilt artifacts (not the GitHub source tree).

**Comment by llemeurfr** [comment]
A gitignore was added by Daniel. This lib, which is adapted to the LCP Basic profile, is kept here for the short term to help implementers building the app easily. Some other way to get the lib will be setup later and the file removed from github.

**Comment by aferditamuriqi** [comment]
I m closing this issue since we have decided to remove the lcplib from this repo
